=== jenesepas/ej_js/lmsgi/tuto4/llamadas.dtd
<!ELEMENT factura (llamadas, mensajes, datos, resumen)>
<!ELEMENT llamadas ANY>
<!ELEMENT llamada ANY>
<!ATTLIST llamada id ID #IMPLIED> 
<!ATTLIST llamada tipo CDATA #IMPLIED> 
<!ELEMENT fechahora ANY>
<!ATTLIST fechahora inicio CDATA #IMPLIED> 
<!ATTLIST fechahora fin CDATA #IMPLIED> 
<!ELEMENT tarificacion ANY>
<!ATTLIST tarificacion duracion CDATA #IMPLIED> 
<!ATTLIST tarificacion importe CDATA #IMPLIED> 
<!ELEMENT destino ANY>
<!ATTLIST destino numero CDATA #IMPLIED> 
<!ELEMENT mensajes ANY>
<!ELEMENT mensaje ANY>
<!ATTLIST mensaje id ID #IMPLIED> 
<!ATTLIST mensaje tipo CDATA #IMPLIED>
<!ELEMENT fechahora ANY>
<!ATTLIST fechahora inicio CDATA #IMPLIED> 
<!ELEMENT tarificacion ANY>
<!ATTLIST tarificacion duracion CDATA #IMPLIED> 
<!ATTLIST tarificacion importe CDATA #IMPLIED>
<!ELEMENT destino ANY>
<!ATTLIST destino numero CDATA #IMPLIED> 
<!ELEMENT contenido ANY>
<!ELEMENT datos ANY>
<!ELEMENT sesion ANY>
<!ATTLIST sesion id ID #IMPLIED> 
<!ATTLIST sesion tipo CDATA #IMPLIED>
<!ELEMENT fechahora ANY>
<!ATTLIST fechahora inicio CDATA #IMPLIED> 
<!ATTLIST fechahora fin CDATA #IMPLIED> 
<!ELEMENT tarificacion ANY>
<!ATTLIST tarificacion duracion CDATA #IMPLIED> 
<!ATTLIST tarificacion importe CDATA #IMPLIED>
<!ELEMENT trafico ANY>
<!ATTLIST trafico kbsubidos CDATA #IMPLIED> 
<!ATTLIST trafico kbbajados CDATA #IMPLIED> 
<!ELEMENT resumen ANY>
<!ELEMENT subtotal ANY>
<!ATTLIST subtotal tipo CDATA #IMPLIED> 
<!ATTLIST subtotal cantidad CDATA #IMPLIED> 
<!ATTLIST subtotal importe CDATA #IMPLIED> 
<!ELEMENT total ANY>
<!ATTLIST total base CDATA #IMPLIED> 
<!ATTLIST total iva CDATA #IMPLIED> 
<!ATTLIST total cuota CDATA #IMPLIED> 
<!ATTLIST total total CDATA #IMPLIED>

=== jenesepas/ej_js/lmsgi/tuto4/Tutoría 20160127 - llamadas (dtd).xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE factura SYSTEM "llamadas.dtd">
<factura>
	<llamadas>
		<llamada id="L00001" tipo="N">
			<fechahora inicio="2016-01-01 01:30:10" fin="2016-01-01 01:34:20" />
			<tarificacion duracion="00:04:10" importe="0.25" />
			<destino numero="987654454" />
		</llamada>
		<llamada id="L00002" tipo="N">
			<fechahora inicio="2016-01-01 01:36:40" fin="2016-01-01 01:37:10" />
			<tarificacion duracion="00:00:30" importe="0.10" />
			<destino numero="987654454" />
		</llamada>
	</llamadas>
	<mensajes>
		<mensaje id="M00001" tipo="N">
			<fechahora inicio="2016-01-01 01:40:15" />
			<tarificacion duracion="00:04:10" importe="0.20"/>
			<destino numero="612454454" />
			<contenido>PUEDES PASAR A RECOGERME??? THX</contenido>
		</mensaje>
	</mensajes>
	<datos>
		<sesion id="S00001" tipo="N">
			<fechahora inicio="2016-01-01 01:55:08" fin="2016-01-01 01:57:25" />
			<tarificacion duracion="00:02:13" importe="0.00" />
			<trafico kbsubidos="332" kbbajados="768" />
		</sesion>
	</datos>
	<resumen>
		<subtotal tipo="llamadas" cantidad="2" importe="0.35" />
		<subtotal tipo="mensajes" cantidad="1" importe="0.20" />
		<subtotal tipo="datos" cantidad="1" importe="0.00" />
		<total base="0.55" iva="21.00" cuota="0.12" total="0.67" />
	</resumen>
</factura>
